from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def draw_bios_screen(angle: float, lighting: str) -> np.ndarray:
    canvas = np.full((360, 560, 3), 28, dtype=np.uint8)
    screen = np.full((250, 410, 3), (20, 45, 115), dtype=np.uint8)
    cv2.rectangle(screen, (8, 8), (402, 242), (210, 225, 255), 2)
    cv2.putText(screen, "MAIN ADVANCED BOOT", (28, 58), cv2.FONT_HERSHEY_SIMPLEX, 0.72, (245, 245, 245), 2)
    cv2.putText(screen, "SECURITY EXIT", (28, 102), cv2.FONT_HERSHEY_SIMPLEX, 0.72, (245, 245, 245), 2)
    cv2.putText(screen, "F10 SAVE AND EXIT", (28, 190), cv2.FONT_HERSHEY_SIMPLEX, 0.58, (235, 235, 180), 1)
    canvas[55:305, 75:485] = screen
    rot = cv2.getRotationMatrix2D((280, 180), angle, 1.0)
    out = cv2.warpAffine(canvas, rot, (560, 360), borderValue=(18, 18, 18))
    if lighting == "dark":
        out = np.clip(out * 0.68, 0, 255).astype(np.uint8)
    elif lighting == "bright":
        out = np.clip(out * 1.18 + 20, 0, 255).astype(np.uint8)
    return out


def generate_bios() -> None:
    bios_dir = ensure_dir(DATA / "bios" / "ami")
    rows = []
    specs = [(0, "normal"), (15, "normal"), (30, "bright"), (45, "dark")]
    for i, (angle, lighting) in enumerate(specs, 1):
        rel = f"ami/synth-{i:02d}.jpg"
        cv2.imwrite(str(DATA / "bios" / rel), draw_bios_screen(angle, lighting))
        rows.append({
            "filename": rel,
            "vendor": "ami",
            "angle_deg": angle,
            "lighting": lighting,
            "top_menu_text": "MAIN ADVANCED BOOT SECURITY EXIT",
            "notes": "synthetic generated by notebooks/generate_synthetic_cv_data.py",
        })
    pd.DataFrame(rows).to_csv(DATA / "bios" / "ground-truth.csv", index=False)


def make_scene(kind: str, frame_idx: int, jitter: int = 0, brightness: float = 1.0) -> np.ndarray:
    frame = np.full((240, 320, 3), 34, dtype=np.uint8)
    color = (50, 95, 190) if kind == "bios" else (35, 150, 70)
    x = 48 + jitter
    y = 42 + jitter // 2
    cv2.rectangle(frame, (x, y), (x + 220, y + 135), color, -1)
    cv2.rectangle(frame, (x, y), (x + 220, y + 135), (230, 230, 230), 2)
    label = "BIOS MENU" if kind == "bios" else "BOOT MENU"
    cv2.putText(frame, label, (x + 20, y + 52), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (245, 245, 245), 2)
    cv2.putText(frame, f"{frame_idx:03d}", (x + 20, y + 95), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (240, 240, 180), 1)
    return np.clip(frame.astype(np.float32) * brightness, 0, 255).astype(np.uint8)


def write_video(path: Path, scenario: str, event_sec: float = 2.0) -> None:
    ensure_dir(path.parent)
    fps = 10
    writer = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (320, 240))
    for idx in range(50):
        t = idx / fps
        kind = "boot" if t >= event_sec else "bios"
        jitter = 0
        brightness = 1.0
        if scenario == "hand-shake":
            jitter = int(5 * np.sin(idx * 1.7))
        elif scenario == "lighting":
            brightness = 0.72 + 0.42 * (idx / 49)
        elif scenario == "rolling-shutter":
            jitter = (idx % 4) - 2
        elif scenario == "ios-autofocus":
            brightness = 1.0 + 0.08 * np.sin(idx / 3)
        writer.write(make_scene(kind, idx, jitter, brightness))
    writer.release()


def generate_live_frames() -> None:
    rows = []
    scenarios = ["normal-change", "hand-shake", "lighting", "rolling-shutter", "ios-autofocus"]
    for scenario in scenarios:
        path = DATA / "live-frames" / scenario / f"{scenario}.mp4"
        write_video(path, scenario)
        rows.append({
            "video_filename": f"{scenario}/{scenario}.mp4",
            "event_timestamp_sec": 2.0,
            "event_type": "screen-change",
            "notes": f"synthetic true scene transition with {scenario} perturbation",
            "scenario": scenario,
        })
    pd.DataFrame(rows).to_csv(DATA / "live-frames" / "ground-truth.csv", index=False)


def quality_image(label: str, idx: int) -> np.ndarray:
    img = make_scene("bios", idx)
    if label == "blur":
        img = cv2.GaussianBlur(img, (17, 17), 0)
    elif label == "dark":
        img = np.clip(img * 0.42, 0, 255).astype(np.uint8)
    elif label == "bright":
        img = np.clip(img * 1.8 + 30, 0, 255).astype(np.uint8)
    elif label == "shake":
        M = np.float32([[1, 0, 14], [0, 1, 4]])
        shifted = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]), borderValue=(34, 34, 34))
        img = cv2.addWeighted(img, 0.55, shifted, 0.45, 0)
    return img


def generate_quality() -> None:
    qdir = ensure_dir(DATA / "live-frames" / "quality-mix")
    rows = []
    labels = ["good"] * 16 + ["blur"] * 8 + ["dark"] * 8 + ["bright"] * 8 + ["shake"] * 8
    for idx, defect in enumerate(labels, 1):
        filename = f"quality-{idx:03d}.jpg"
        cv2.imwrite(str(qdir / filename), quality_image(defect, idx))
        rows.append({
            "filename": filename,
            "label": "good" if defect == "good" else "bad",
            "defect_type": "none" if defect == "good" else defect,
        })
    pd.DataFrame(rows).to_csv(qdir / "labels.csv", index=False)


def main() -> None:
    generate_bios()
    generate_live_frames()
    generate_quality()
    print("Synthetic CV data generated under data/. Raw binaries are ignored by git.")


if __name__ == "__main__":
    main()
